version: '3'
services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: patient_registration
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"